services:
  # Backend Web Service
  - type: web
    name: amazon-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000

  # Frontend Static Site
  - type: web
    name: amazon-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API
        fromService:
          type: web
          name: amazon-backend
          property: host
        value: https://${amazon-backend}.onrender.com/api
